### ISSUE TITLE
Dev - Test - Prod Data Transfer Endpoint

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#102]
It would be extremely helpful to have a one stop shop endpoint to transfer data between dev, test and prod mongodb instances or have some automation pipeline set up where this happens without us even thinking about it.  We do not often utilize this behavior but every now and then a data error occurs and we have to take down prod to comb the data and provide the fix.  It would be much better to instead make a copy of the DB on another server to test and find data incongruities, then apply a data patch of the fixed objects onto the prod mongodb.  This would decrease down time and help mitigate disaster scenarios for prod data.

**Comment by cubap** [comment]
Now that this is on the same Mongo, it should be simple. You can `mongodump` either direction or `mongorestore` into a temp db to do the damage.
