### ISSUE TITLE
__rerum must have its own context

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#106]
We cannot put `@context:http://store.rerum.io/v1/context.json` on the objects themselves, this is left to the user when they create the object.  Objects MAY NOT be JSON-LD, we do support basic JSON (no `@context` on the object).

In the past, we considered forcing `@context` onto the object when none existed, but chose not to.  I believe this thought should be revisited.

`@context` is allowed to be an Array.  IIIF supports this and notes that the presentation API context URL must be first in the array.  This would allows us to implant the `@context` onto objects by ensuring our `@context` URL is not first.

The context file for RERUM is currently being rewritten under this realization.  I am making a `@context` that at least explains the `__rerum` field.  

If an object is not JSON-LD (it does not have a top level `@context`) then the `__rerum` key does not need a @context.  If it is, then `__rerum` needs a context to expand properly.

We do NOT want to play the game of having the context file in RERUM as a top level `@context`.  Our context file would bloat beyond what any JSON-LD processor could handle because it would be so large.  To get an idea of what I mean, compare our current context file to the Presentation API 3 context file.

https://iiif.io/api/presentation/3/context.json
http://store.rerum.io/v1/context.json

Since we are positive agnostic, our context file would have to include not only all the IIIF contexts (`Collection:{}`, `Manifest:{}`...) but also all of schema (`Person:{}`, `Place:{}`, `Thing:{}`) and any other encoding that could be used.  We place no restrictions on what can be saved or what encoding is used and cannot possibly hope to have a top level RERUM `@context`.  I tested by doing this and expanding our @context and crashed the JSON-LD playground.

**Comment by cubap** [comment]
I feel dumb. I thought the __rerum contgext was already scoped to __rerum only. We can discuss addign a top level context, but that should be a different issue.
________________________________

**Comment by thehabes** [comment]
Yes that is its own issue.  

Yeah I feel dumb too, I forgot all about the damn thing.  I went into JSON-LD yesterday to play with some with the rerum context and blew it up.  So I started looking into how we might fix this.  I started with forcing `@context` at the top level and found out quickly that is a no go.  I want to scope it into `__rerum`.

Once I did that, I realized it wasn't even close to being correct so I started hammering it.  It is very close to being correct but made some term choices we will need to go over.

Yes, a top level rerum `@context` is its own issue.  Perhaps its own milestone, since it would be a daunting task.

**Comment by thehabes** [comment]
We will have to plan this carefully though.  We will have to write a script to go heal every object that was already created incorrectly.  Either that or have handlers to heal them automatically as they come through broken.  We will talk about it, let's wait until the standup today.

**Comment by thehabes** [comment]
Scoped contexts do not appear to work.  

Go to https://json-ld.org/playground/
Use http://devstore.rerum.io/v1/id/5e7227b0e4b048b501c26687

You will see __rerum is still scoped to the `http://schema.org/` top level context.  :(

**Comment by thehabes** [comment]
We have a working context.  Now we need to update the API Java code to include this context any time __rerum is generated.

**Comment by thehabes** [comment]
It is very, very very important the context file have an entry for __rerum.  It makes a special case functionality work to everyones benefit.  We do this https://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld, so we need to mention __rerum in the context file for this situation.
