### ISSUE TITLE
__rerum context and API need to align

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#107]
Looking at the __rerum field, the values the API puts there does not line up with @context.  Things that are booleans have an empty string instead of false, sometimes it is `"true"` instead of `true`, etc.  We need to update the API functions that create/manipulate the `__rerum` field.  Once we have a http://store.rerum.io/v1/context.json we agree on, we must update the code the align with what it states.

**Comment by thehabes** [comment]
configureRerumOptions()
overwriteObject()
putUpdateObject()
deleteObject()

We did a decent job of keeping interactions with __rerum a modular task.  These are the only methods that need visited to change what happens with that field.

**Comment by thehabes** [comment]
We have one up that we agree on.  Two more steps before this is resolved:
1. Update RERUM API Java code to initiate `__rerum` values of the correct data type.
2. __rerum is incorrect for all existing objects in the alpha collection.  We need to write a script that updates these objects so they have the correct data type.

This needs to be planned and performed with care.

**Comment by cubap** [comment]
1.  I suggest in the API, we just store `__rerum` and only add the full path (which will probably definitely change) when we send it out.
  2.  We disregard `__rerum` on saving, so it will be rebuilt correctly if there are any updates. We may need to add `__rerum.@context` to them all, but it isn’t the end of the world if we don’t.

**Comment by thehabes** [comment]
It seems like the immediate course of action is to update the Java code under the scope of this ticket.  

Outside of the scope of this ticket are objects that already exists in RERUM who have __rerum like
```JSON
__rerum" : {
    "alpha" : "true",
    "APIversion" : "0.8.0",
    "createdAt" : 1584539568006,
    "isOverwritten" : "",
    "isReleased" : "",
    "history" : {
      "next" : [ ],
      "previous" : "",
      "prime" : "root"
    },
    "releases" : {
      "next" : [ ],
      "previous" : "",
      "replaces" : ""
    },
    "generatedBy" : "http://devstore.rerum.io/v1/id/5afeebf3e4b0b0d588705d90"
  }
```

They will be a bit off once we inject @context into the __rerum field because they won't comply to the stated expected values.  

- `isOverwritten` and `isReleased` are supposed to be booleans, so they should be `false` by default instead of `""`.  `xsd:boolean !== xsd:string`.
- `createdAt` context says its values is a `xsd:dateTime`, which it does not appear to be.  `xsd:dateTiime !== xsd:integer`
- `alpha` context says it is a `xsd:boolean` but is in fact a string.  `xsd:boolean !== xsd:string.

These will be ticketed elsewhere and be non-blocking for this issue.
