### ISSUE TITLE
`__rerum` key should be complete IRI

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#109]
https://github.com/CenterForDigitalHumanities/rerum_server/blob/master/API.md#__rerum

This is needed when we return objects to an id request or query

**Comment by thehabes** [comment]
So all CRUD responses will return objects like `obj["__rerum"]` in their response, but getByProperties and getById will return objects like `obj["https://github.com/CenterForDigitalHumanities/rerum_server/blob/master/API.md#__rerum"]`?  Something about that feels wrong, the response should always be formatted the same.

**Comment by thehabes** [comment]
I think either all `response.out` moments do it or none of the `response.out` moments do it.  If we are going to make it the expanded IRI, it should be so for all returned object representations.

**Comment by cubap** [comment]
All the responses. I mean that in the database, we shouldn't have `https://github.com/CenterForDigitalHumanities/rerum_server/blob/master/API.md#__rerum` because that is not the place we want to keep our vocabulary long-term. If we just store `__rerum` we can update it as we need to and document for developers to look for the key ending in this string.

**Comment by thehabes** [comment]
Yep, on board.  I am going to unassign you because I will do it along with #106 .

**Comment by thehabes** [comment]
@cubap This causes cyclical context errors.  It does not pass in the JSON-LD playground given the current context.json.

**Comment by thehabes** [comment]
@cubap nope, its @thehabes adding the Agent it in the way he did.  On it.
