### ISSUE TITLE
Connect `ObjectAction.saveNewObject()` to DynamoDB

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#128]
Enable AWS create for a new item in DynamoDB. Cleanup within `ObjectAction.java` to relocate Dynamo and Mongo references into abstraction (#127).

Proving it works includes firing the `create.action` servlet (via TinyThings, if you like) and showing the resulting object with an `@id` and `__rerum` addition.

**Comment by cubap** [comment]
These types of JSON objects should be able to be saved and retrieved in the same form.

_Single Simple Key-Value Pairs_
```json
// Strings
{
  "string": "value"
}

// Integers
{
  "int": 5
}

// Numbers (I'll assume trouble would come with 0.0000000001)
{
  "float": 5.1
}

// Boolean
{
  "is": false
}
```

_Simple Objects_
```json
{
  "string": "value",
  "int": 5,
  "is": false
}
```

_Nested Objects and Arrays_
```json
{
  "array": ["string", 5, 5.1, false, { "key": "value" } ],
  "map": {
      "string": "value",
      "int": 5,
      "is": false
  }
}
```

**Comment by thehabes** [comment]
And don't forget

```JSON
{
    "hello": null,
    "hey": ["you", null],
    "how.dy":{"person":null, "names":[null, "fred", {"name":null}]}
}
```

**Comment by cubap** [comment]
Slow down, now. We’re trying to replicate functionality. We’ll address the other bugs once we’ve got that done.
