### ISSUE TITLE
missing items from context.json

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#137]
Deleted terms `deletor` and `object` are missing. There may be others in some corners of the API yet.

**Comment by thehabes** [comment]
![image](https://user-images.githubusercontent.com/3287006/91222821-5bc8b180-e6e5-11ea-9ef0-cc85847be4dd.png)

**Comment by cubap** [comment]
http://ongcdh.org/posts/development/versioning-in-rerum/

The Movations "releasing" and "working" should be included as well.

**Comment by thehabes** [comment]
Motivations are not scoped in `__rerum`.  It is up to the client who is creating the Annotations that use those motivations to extend them properly through their own context or context scoping.  RERUM could do such a thing and impose a context onto every object being saved.  See #120
