### ISSUE TITLE
Test TinyThings

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#183]
poke all endpoints
- DEV => IMG
- PRD2 => IMG

**Comment by thehabes** [comment]
TT on `f-vl-cdh-dev-01` using a RERUM `v1` API on `f-vl-cdh-dev-01` connecting to MongDB on `f-vl-cdh-img-01`
- DEPLOY 👍 
- create 👍 
- update 👍 
- overwrite 👍 
- delete 👍 
- query 👍 
- import 👍 

TT on `f-vl-cdh-prd-02` using a RERUM `v1` API on `f-vl-cdh-prd-02` connecting to MongDB on `f-vl-cdh-img-01`
- DEPLOY 👎 
- create ?
- update ?
- overwrite ?
- delete ?
- query ? 
- import ?
