### ISSUE TITLE
PRD-02 connection to IMG-01 Mongo

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#185]
confirm and enable access to IMG-01 from PRD-02

**Comment by thehabes** [comment]
Connection Refused.  This is blocking #188.  Will investigate.

**Comment by cubap** [comment]
https://ongcdh.slack.com/archives/D0109V556BB/p1613587103060300

Habes  12:38 PM
Here is the additional application stack

* http://test-store.rerum.io/prd02-img01/ is a rerum_server deployed on prd02.  It uses the Mongo connection string to connect with img01.
* http://tiny-test.rerum.io/test-app is a TinyThings deployed on prd01.  It uses the http://test-store.rerum.io/ API, which is deployed on prd-02.
* They use sandbox and bot attribution just like the applications deployed on dev, and so share the same access_token as the application stacks on dev.  This is to ensure uniform attribution in the test and dev database that these production-level and development-level test deploys talk to.
