### ISSUE TITLE
Cleanup DNS Records

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#194]
Clean up the records in Google Domains

**Proposed removal list**
- `aws-dev` CNAME
- `object` Sub-domain forward
- `devstore-atlas` A
- `devstore-img01` A
- `dynamo` A
- `dynamo-on-aws` A
- `dynamo-on-dev` A
- `leaflet` A
- `old` A
- `test-store` A
- `tiny-test` A
- `tinydev-atlas` A
- `tinydev-img01` A
- `tomcat10` A

Doublecheck VirtualHosts in httpd.conf, cleanup the ones involved with records

Doublecheck JkMounts (httpd.conf, mod_jk.conf), cleanup the ones involved these records

**Comment by cubap** [comment]
🔥 burn it
