### ISSUE TITLE
Move v0 data

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#195]
Move `db.annotationstore` and `db.acceptedServer` data from prd-02 mongo to img-01 mongo.

**Comment by cubap** [comment]
The data has been moved, but I do not believe the lookup application is pointing there yet.

**Comment by cubap** [comment]
@thehabes can you confirm this is still pending?

**Comment by thehabes** [comment]
Still pending.  Need to grab the Open Annotation Store code off sourceforge and snag the properties file from prd-02 ([webapps/annotationstore](http://165.134.105.29/annotationstore)).  Then we have to code up that new connection in the old library.  That could be a bit tricky, but I bet we can do it.
