### ISSUE TITLE
Expected return on queries

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#28]
Given a TPEN query like "show me all the annotations `on:<SomeCanvas>`". The current logic would be expected to return the existing transcription, but also all previous versions of all the lines. Does this make sense?

In TPEN (this example), we would probably not run the query, but access the annotations through the `sc:AnnotationList`, avoiding this issue. Would we expect any application to be this deft? Is it overload to return everything?

If we filter the results at all, branches create some issues. We can't just take the most recent and it isn't really helpful to just get the `prime` back. It also seems expensive to sort through for just hte most recent on each branch... maybe.

**Comment by Domhnall101** [comment]
If I were running that kind of search I would expect to have some structure to my results. For instance a t-pen like transcription would come back with the most recent annotations but with each annotation having a link call up the history of that annotation. With the ability to travel along  that history chain  and at any point to stop and view the concurrent annotations  a snap shot as it were. There is also a need I think to make available deadheaded annotation chains too but graphically subdued not to overwhelm the user with dead ends.
OUR search could supports searching sc:AnnotationList as a first level which would help us structure the representation of the data and then give the user the option to call up additional annotations that are not in the sc:AnnotationList (I'm assuming branching a manifest would cause this to happen but I'm happy to be corrected in that)

**Comment by cubap** [comment]
https://lh3.googleusercontent.com/1J1loKVm0VzTDPpztbFZtQxnvIFYC5DkLssMtj1E0H_b9IP0mOmljOQ1PFAeHbMQM_E5c6XegXXG7mptRr-co_ealYOVF_lgK0HG7m_Xl9Q7FlMxs4fOWCBosekIquyYH8AvBUwY1p8ytjrdmyrfXQgVj1zB0Ukmx43qL9pCE8O6jm2W69mqnvxQhSA0N3w3yumOCUKwEQHAUtYkgnjHW2d3M4TymWrlIgOI9SouxbtKFa0LcYtDscSequQTQ98q33qQlvPD4hO1aEb8Yn67XfLRMJ6ugABKrwmuspGqo57m_OI3eRZOuv8tIMQOxhr2UxP0bIOYvl_N4MO1_N8IDZgQHlRGTpvf_udEITOW4G7MUslnCg2Ev_V4iDBRNGVs02SV2d7ME1HOHEHb7ATczz256zaVPJ0nYjXCmAdphUXoAWG6SGPcSLWrwWLVCtyJ0x8PMsv1Fmf5FsMvb4mNgAz-hSAEk0swACLWraFP0ct7RIIPzF4KNQyyF7IihCbFQSyE1B1lk2U1CctZSQvScKTZXvHwaUcRW2t6CcHu26loYvxGYwmC7qr7rmxdDEZ3jTxQB9rqXQJVzHJOWS17AgzbcOzDI-8AkfnM1B6ZKQ=w945-h709-no
![image](https://user-images.githubusercontent.com/1119165/33897979-9959b300-df2c-11e7-81ff-28e0e63b52fc.png)

**Comment by cubap** [comment]
So applications should be aware that the retrieval of queries can be messy. Something like TPEN looks for an `sc:AnnotationList` with IDs, to avoid making queries. There are very few ways in which a user can access these queries in a meaningful way from RERUM, but the applications that use it should be better.

The default response to a query will remove any older versions from the response. This isn't immediately known from the query results, so additional filtering is required. Once the results are obtained, they should probably be clustered by `history.prime` and definitely all results with values for `history.next` should be scrubbed.
