### ISSUE TITLE
PATCH set

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#34]
updateAnnotation only works on keys that already exist on the object.  We need to create a set() action for setting new keys.

**Comment by thehabes** [comment]
Consider handling __rerum as a special case.  Set and Unset are extremely detrimental to this field.

**Comment by cubap** [comment]
`__rerum` is definitely a special case. There is no user action to change it directly, so it can be excluded from all these processes.
