### ISSUE TITLE
Deleting an Object

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#39]
![image](https://user-images.githubusercontent.com/1119165/34277492-969fe3be-e66b-11e7-90b6-937d6773e049.png)

**Comment by cubap** [comment]
### First Principles

- Deleted objects MUST NOT be obliterated;
- Application MUST NOT be able to unintentionally use a deleted object;
- Only the generating application may delete an object;
- Versioning history MUST heal around a deleted object; and
- Deleted objects MUST maintain a reference to their state immediately before deletion.

### Requests and Responses

- getByID() : returns an object of the "deleted" template with the original object embedded;
```json
{   "@id" : "http://sameID",
    "_id" : "sameID",
    "__deleted" : {
        "time" : 5498113521, // time of deletion 
        "object" : { } // exact copy of previous state
}
```
- **getByProperties()** :  MUST NOT include any deleted objects
- **getAllAncestors(), getAllDescendants()** : MUST NOT include any deleted objects
- **getAllAncestors(), getAllDescendants()** : MUST return 410 GONE when run against a deleted object
- **update.action** : fail 403 FORBIDDEN
- **delete.action** : fail 403 FORBIDDEN

### Logic

When an object is deleted, it will be in one or more of three states: 1) it is the prime version; 2) it is the most recent version on a branch; 3) it is an intermediate version. To remove an object version (`DO`) from the version history after deletion, several changes are needed around it:
- If `DO.__rerum.history.previous` has a value, then that referenced version must have the `DO[@id]` replaced from its `..__rerum.history.next` array with the values from `DO.__rerum.history.next`;
- If `DO.__rerum.history.next` has values, then each referenced version must have the `DO[@id]` replaced from its `..__rerum.history.previous` with the value from `DO.__rerum.history.previous`;
- If `DO.__rerum.history.prime` equals "root" and `DO.__rerum.history.next` has values, then each referenced version must have the `DO[@id]` replaced from its `..__rerum.history.prime` with "root" _and_ all downstream versions must be updated to refer to its `@id` instead of `DO[@id]` in `..__rerum.history.prime`; and
- No impacted object version will be recorded as overwritten or modified when updated in this process.

**Comment by thehabes** [comment]
A DELETE should be possible via
- Provided id in request header
- Provided id in request body
- Provided JSON(-LD) object in body

Via web annotation standards, a successful DELETE should respond NO CONTENT (204)

A DELETE should fail if
- The object or id to delete is already flagged as deleted in RERUM (405)
- The id provided does not exist in RERUM (404)
- The provided object does not exist in RERUM (404)
- The deleting agent was not the creator of the object (401)
- Any other standard request failure already implemented (400)

A DELETE should warn if
- `DO.__rerum.history` does not exist
- `DO.__rerum.history.next` id(s) cannot be found in RERUM
- `DO.__rerum.history.previous` id cannot be found in RERUM
- `DO.__rerum.history.next` object(s) cannot be updated in RERUM
- `DO.__rerum.history.previous` object cannot be updated in RERUM

As this may be heading towards some serious versioning pollution.
