### ISSUE TITLE
large object seems to be unGETable

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#80]
~~~~
SEVERE [ajp-nio-8109-exec-43] edu.slu.action.ObjectAction.getByID null
 com.fasterxml.jackson.databind.JsonMappingException: Object is null (through reference chain: net.sf.json.JSONObject["sequences"]->net.sf.json.JSONArray[0]->net.sf.json.JSONObject["canvases"]->net.sf.json.JSONArray[0]->net.sf.json.JSONObject["images"]->net.sf.json.JSONArray[0]->net.sf.json.JSONObject["motivation"]->net.sf.json.JSONNull["empty"])
~~~~

Error when trying to `GET` new object `http://devstore.rerum.io/v1/id/5b5a20fde4b0f32b4d011e06`

The object was created in Tiny Things, is findable in the mongo command line, appears to have the right `@id` assigned, but errors oddly (no return to the browser) when GETting.

**Comment by thehabes** [comment]
Because of #82

**Comment by thehabes** [comment]
This is actually #82 because this object contains a `null`
