### ISSUE TITLE
Replace specialty batch methods with single method

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server#9]
## Batch Create/Update

Accept an array of objects for simple save/update. This replaces `batchSaveMetadataForm()` and `batchSaveFromCopy()`. Iterate through each and take appropriate action:

* **no `@id`** New item. Set `__rerum` properties and save first version.
* **`@id` from RERUM** Existing item. Set `__rerum` properties on new version and queue an update for `history.next` on previous object version.
* **`@id` from external source** External item.  Set `__rerum` properties as if first version and consider flagging external reference as... ?

The challenge here are that we are leveraging the Mongo batch, which creates at once, not leaving us the chance to update the previous object.

**Comment by thehabes** [comment]
That is how the batch update works.  The return of the batch update is very flexible.  We can return an array  of objects like [{orginal@id: bleh/id/123, new@idFromUpdate:bleh/id/234}, ...] and pass that array to another function that knows to push new@idFromUpdate into orginal@id.__rerum.history.next.  You will see in the bulk update functions now how I control what it returns and I could just as easily make it something like that.

**Comment by cubap** [comment]
Yup. This will likely be used internally too, when we do things like save an `sc:AnnotationList` so it will be good to align the process for both cases.
